### ISSUE TITLE
Snow invisible: Add configuration options?

### ISSUE THREAD

**Issue by andyboeh** [mprins/dokuwiki-plugin-snow#33]
## environment

  - php version: 7.3
  - dokuwiki version: 2018-04-22 Greebo
  - plugin version / date: 2019-10-24
  - list of any other plugins (apart from bundled plugins): 
  
## expected behaviour

visible snow flakes

## actual behaviour

The snow flakes are invisible. They have a z-Index of 0 while #sb-site uses z-Index 1, hence they are behind the visible area. This might also be caused by our template, it's a heavily customized bootstrap-based template. As a quick fix, I edited snowflakes-min.js and changed the z-Index to 20.

I think it would be a good idea to add configuration options to the PlugIn, since the snowstorm script supports some options. If I find the time, I might come up with a PR.

**Comment by mprins** [comment]
yeah, playing with z-index is always a tricky thing to do
